CREATE TABLE IF NOT EXISTS `VEHICLE` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    DTYPE VARCHAR(31) NOT NULL,
    brand VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    year INT NOT NULL,
    plate VARCHAR(20) NOT NULL,
    mileage_km INT NOT NULL,
    engine_displacement_cc INT NOT NULL,
    car_type VARCHAR(30) NULL,
    number_of_doors INT NULL,
    passenger_capacity INT NULL,
    trunk_capacity_liters INT NULL,
    truck_type VARCHAR(30) NULL,
    load_capacity_tons INT NULL,
    axles INT NULL,
    last_maintenance_at TIMESTAMP NULL,
    last_maintenance_cost DECIMAL(10,2) NULL,
    last_maintenance_by VARCHAR(120) NULL,
    CONSTRAINT uk_vehicle_plate UNIQUE (plate)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
